<div id="primary-content">
	<div class="wrapper">
		<article>
			<a href="#"><img src="assets/images/paris.jpg" alt="Torre Eiffel" /></a>
			<h3>Featured Content</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod leo a nibh dignissim tincidunt. Nam ultricies odio ac neque suscipit volutpat. Ut dictum adipiscing felis sed malesuada. Integer porta sem nec nibh hendrerit imperdiet. </p>

		</article>
	</div>
</div>
<div id="secondary-content">
	<div class="wrapper">
		<article style="background-image: url('assets/images/cinema.jpg');">
			<div class="overlay">
				<h4>Cine</h4>
				<p><small>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod leo a nibh dignissim tincidunt nam.</small></p>
				<a href="#" class="more-link">View more</a>
			</div>
		</article>
		<article style="background-image: url('assets/images/mtb.jpg');">
			<div class="overlay">
				<h4>Deportes</h4>
				<p><small>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod leo a nibh dignissim tincidunt nam.</small></p>
				<a href="#" class="more-link">View more</a>
			</div>
		</article>
	</div>
</div>
<div class="clear"></div>
<div id="secondary-content">
	<div class="wrapper">		
		<article style="background-image: url('assets/images/pasillo.jpg');">
			<div class="overlay">
				<h4>Libros</h4>
				<p><small>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod leo a nibh dignissim tincidunt nam.</small></p>
				<a href="#" class="more-link">View more</a>
			</div>
		</article>
		<article style="background-image: url('assets/images/concierto3.jpg');">
			<div class="overlay">
				<h4>Música</h4>
				<p><small>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod leo a nibh dignissim tincidunt nam.</small></p>
				<a href="#" class="more-link">View more</a>
			</div>
		</article><div class="clear"></div>
	</div>
</div>
