<!DOCTYPE html>
<html>
	<!-- HEAD -->
    <body>
    	<section id="container">
    		<!-- HEADER -->
    	    
		<!--Modal para iniciar sesion de usuario -->	
		<div id="modalInicio" class="modalmask">
    		<div class="modalbox movedown">
		        <a href="#close" title="Close" class="close">X</a>
		        <h3>Inicio de sesión</h3>
		        <p><small>Introduzca sus datos para iniciar la sesión</small></p>
		        <div id="formInicio">
					<form action="">
						<label for="usuario">Usuario:</label>
						<input type="text" id='usuario' placeholder="Introduzca su correo electrónico">
						<label for="password">Contraseña:</label>
						<input type='password' id='password' placeholder="Introduzca su contraseña">
						<input type="submit" value='Iniciar sesión'>
					</form>	
				</div>
		    </div>
		</div>
		<!--Modal para registrarse como usuario -->	
		<div id="modalRegistro" class="modalmask">
    		<div class="modalbox movedown">
		        <a href="#close" title="Close" class="close">X</a>
		        <h3>Registro de usuarios</h3>
		        <p><small>Introduzca los siguientes datos para crear su usuario</small></p>
		        <div id="formRegistro">
					<form action="">
						<label for="nombre">Nombre:</label>
						<input type="text" id='nombre' placeholder="Nombre">
						<label for="apellidos">Apellidos:</label>
						<input type="text" id='apellidos' placeholder="Apellidos">
						<label for="email">Correo electrónico: *(Será su usuario para iniciar sesión)</label>
						<input type="text" id='email' placeholder="Introduzca su correo electrónico">
						<label for="password">Contraseña:</label>
						<input type='password' id='password' placeholder="Introduzca su contraseña">
						<input type="submit" value='Registrarse'>
					</form>	
				</div>
		    </div>
		</div>

		<section>			
		  	<!-- CONTENT -->

		</section>
		
		<!-- FOOTER -->

    	</section>
    </body>

    
</html>