<!DOCTYPE html>
<html>
	<!-- HEAD -->
	<head>
    <title>Proyecto eNubes</title>
    <meta charset="utf-8" />
    <meta content="miguelangelvr" name="author" />
	<meta content="Proyecto para eNubes" name="description" />
	<meta content="deporte, música, libros, cine" name="keywords" />
	<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
	<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	<link href='http://fonts.googleapis.com/css?family=Crete+Round' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="assets/css/reset.css">
	<link rel="stylesheet" type="text/css" href="assets/css/style.css">
	<link rel="stylesheet" type="text/javascript" href="assets/js/js.js">
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/bs-3.3.5/jq-2.1.4,dt-1.10.10,b-1.1.0,r-2.0.0/datatables.min.css"/> 
	<script type="text/javascript" src="https://cdn.datatables.net/s/bs-3.3.5/jq-2.1.4,dt-1.10.10,b-1.1.0,r-2.0.0/datatables.min.js"></script>
</head>
    <body>
    	<section id="container">
    		<!-- HEADER -->
    		<header>
	<div class="wrapper">
		<h1>Noticias eNubes</h1>
		<nav>
		<?php if(!isset($_SESSION['nombre'])): ?>
			<ul>						
				<li><a href="#modalInicio">Inicie sesión</a></li>
				<li><a href="#modalRegistro">Regístrese</a></li>
			</ul>
		<?php else : ?>
			<ul>						
				<li>Logueado como <?php print $_SESSION['nombre']; ?></li>
				<li><a href="#modalCerrar">Cerrar sesión</a></li>
			</ul>
		<?php endif; ?>
		</nav>
		<div class="clear"></div>
		<nav class="navDown">
			<ul>
				<li><a href="/">Inicio</a></li>
				<li><a href="?c=usuario&a=index">Cine</a></li>
				<li><a href="?c=noticia&a=index">Deportes</a></li>
				<li><a href="#">Libros</a></li>
				<li><a href="#">Música</a></li>					
			</ul>			
		</nav>
	</div>
</header>
    	    
		<!--Modal para iniciar sesion de usuario -->	
		
		<!--Modal para registrarse como usuario -->	
		

		<section>			
		  	<!-- CONTENT -->

		</section>
		
		<!-- FOOTER -->

    	</section>
    </body>    
</html>